version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: web
    ports:
      - "5173:5173"
    depends_on:
      - postgres
    volumes:
      - ./web:/usr/src/app

volumes:
  postgres-data:
